CONNECTION_ERROR_MESSAGE = 'Could Not Connect!!!'
GLOBAL_NAMESPACE_URL = '{}/ros/get_global_namespace'
LOGIN_PAGE_TITLE = 'Log in Page'
POST_METHOD = 'POST'
TITLE_KEY = 'title'
FORM_KEY = 'form'
SUCCESS_KEY = 'success'
LOGINPAGE_TEMPLATE = 'loginPage/loginPage.html'