CONNECTION_ERROR_MESSAGE = 'Could Not Connect!!!'
GLOBAL_NAMESPACE_RESPONSE_KEY = 'global_namespace'
LOGIN_PAGE_TITLE = 'Log in Page'
POST_METHOD = 'POST'
TITLE_KEY = 'title'
FORM_KEY = 'form'
SUCCESS_KEY = 'success'
LOGINPAGE_TEMPLATE = 'loginPage/loginPage.html'

GLOBAL_NAMESPACE_API_URL = '{}/ros/get_global_namespace'
ARM_API_URL = '{}/ros/{}/navigation/arm'
TAKEOFF_API_URL = '{}/ros/{}/navigation/take_off'
LAND_API_URL = '{}/ros/{}/navigation/land'